// components/forms/SmallSelect.tsx
import { Listbox, Transition } from "@headlessui/react";
import { Fragment } from "react";

interface SelectOptions {
	items: SelectItem[];
	selected: SelectItem;
	setSelected: React.Dispatch<React.SetStateAction<SelectItem>>;
	direction?: SelectDirection;
}

export enum SelectDirection {
	Right = "right",
	Left = "left"
}

interface SelectItem {
	text: string;
	value: string;
	icon: any;
	description?: string;
}

export default function SmallSelect({ items, selected, setSelected, direction = SelectDirection.Right }: SelectOptions) {
	return (
		<Listbox
			value={selected.value}
			onChange={value => {
				const selectedItem = items.find(item => item.value === value);
				if (selectedItem) {
					setSelected(selectedItem);
				}
			}}>
			<div className="relative z-50 mt-1 font-inter">
				<Listbox.Button className="flex relative flex-row gap-x-1 items-center p-2 text-gray-600 rounded duration-200 cursor-default dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700">
					<selected.icon strokeWidth={2} className="w-6 h-6" aria-hidden="true" />
				</Listbox.Button>
				<Transition
					as={Fragment}
					enter="ease-out duration-200"
					enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
					enterTo="opacity-100 translate-y-0 sm:scale-100"
					leave="ease-in duration-200"
					leaveFrom="opacity-100 translate-y-0 sm:scale-100"
					leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95">
					<Listbox.Options
						className={`overflow-auto absolute z-30 mt-1 w-64 text-base bg-white rounded-md border dark:border-gray-700 bg-dark font-inter ${
							direction == SelectDirection.Left && "right-0 origin-top-right"
						}`}>
						{items.map(item => (
							<Listbox.Option
								key={item.value}
								className={`${
									item.value === selected.value &&
									"bg-orange-100 dark:bg-gray-800"
								} flex relative flex-row gap-x-3 items-center p-2 text-gray-800 dark:text-gray-100 duration-200 cursor-default select-none hover:bg-gray-100 dark:hover:bg-gray-700`}
								value={item.value}>
								<item.icon
									className="w-4 h-auto text-gray-500"
									aria-hidden={true}
								/>
								<div className="flex flex-col">
									<span className="text-sm font-semibold">{item.text}</span>
									<span className="text-sm text-orange-700 dark:text-orange-200">
										{item.description ?? ""}
									</span>
								</div>
							</Listbox.Option>
						))}
					</Listbox.Options>
				</Transition>
			</div>
		</Listbox>
	);
}

// components/select/SmallSelect.vue
<script lang="ts">
import {
	Listbox,
	ListboxButton,
	ListboxOption,
	ListboxOptions,
} from "@headlessui/vue";

export enum SelectDirection {
	Right = "right",
	Left = "left",
	Center = "center",
}

export enum SelectOrientation {
	Up = "up",
	Down = "down",
}

export interface SelectItem {
	text: string;
	value: string;
	icon: string;
	description?: string;
}
</script>

<script setup lang="ts">
interface SelectProps {
	items: SelectItem[];
	defaultValue: number;
	direction?: SelectDirection;
	orientation?: SelectOrientation;
	name?: string;
}

const props = defineProps<SelectProps>();
const emit = defineEmits(["update:model-value"]);

const selected = ref<SelectItem>(props.items[props.defaultValue]);
</script>

<template>
	<Listbox
		v-model="selected"
		:name="name"
		as="div"
		class="relative"
		@update:model-value="value => emit('update:model-value', value)">
		<ListboxButton
			class="flex relative flex-row gap-x-1 items-center p-2 text-gray-600 rounded duration-200 cursor-default dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-dark-700">
			<Icon
				:name="selected.icon"
				:stroke-width="2"
				class="w-6 h-6"
				aria-hidden="true" />
		</ListboxButton>
		<Transition
			appear
			enter-from-class="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
			enter-to-class="opacity-100 translate-y-0 sm:scale-100"
			enter-active-class="ease-out duration-100"
			leave-active-class="ease-in duration-100"
			leave-from-class="opacity-100 translate-y-0 sm:scale-100"
			leave-to-class="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95">
			<ListboxOptions
				:class="[
					'absolute z-30 shadow-lg mt-1 w-64 text-base rounded-md overflow-hidden bg-gray-100/75 dark:bg-dark-800/75 backdrop-blur-md',
					direction === SelectDirection.Left &&
						'right-0 origin-top-right',
					direction === SelectDirection.Center &&
						'right-0 origin-top-right translate-x-[50%]',
					orientation === SelectOrientation.Up && 'bottom-[110%]',
				]">
				<ListboxOption
					v-for="item in items"
					:key="item.value"
					:value="item"
					:class="[
						item.value === selected.value &&
							'bg-orange-100 dark:bg-orange-500/10',
						'flex relative flex-row gap-x-3 items-center py-2 px-3 text-gray-800 dark:text-gray-100 duration-200 cursor-default select-none hover:bg-gray-200 dark:hover:bg-dark-700/75',
					]">
					<Icon
						:name="item.icon"
						class="w-5 h-auto text-gray-500"
						aria-hidden="true" />
					<div class="flex flex-col">
						<span class="text-sm font-semibold font-poppins">
							{{ item.text }}
						</span>
						<span
							class="text-sm text-orange-700 dark:text-orange-200">
							{{ item.description ?? "" }}
						</span>
					</div>
				</ListboxOption>
			</ListboxOptions>
		</Transition>
	</Listbox>
</template>
