// components/feed/Conversation.tsx
/* eslint-disable @next/next/no-img-element */
import { AuthContext } from "components/context/AuthContext";
import WithLoader from "components/loaders/WithLoader";
import DummyStatus from "components/posts/DummyStatus";
import { Post } from "components/scroll/InfiniteScrollPosts";
import { Entity } from "megalodon";
import { arrayToTree } from "performant-array-to-tree";
import { useContext, useEffect, useState } from "react";

export const Conversation = ({ id }) => {
	const [ancestors, setAncestors] = useState<Entity.Status[]>([]);
	const [posts, setPosts] = useState<Entity.Status[]>([]);
	const [descendants, setDescendants] = useState([]);
	const client = useContext(AuthContext);

	useEffect(() => {
		client.getStatus(id).then(data => {
			setPosts([data.data]);

			client.getStatusContext(id).then(context => {
				setAncestors(context.data.ancestors);
				setDescendants(
					arrayToTree(context.data.descendants, {
						id: "id",
						parentId: "in_reply_to_id",
						rootParentIds: {
							[id]: true,
						},
						dataField: null,
					}) as any,
				);
			});
		});

		return () => setPosts([]);
	}, [client, id]);

	return (
		<>
			{posts.length > 0 ? (
				<div className="flex overflow-y-auto flex-col gap-y-5 py-4 w-full h-full no-scroll">
					<div className="flex flex-col gap-y-4 px-6">
						{ancestors.map(post => (
							<Post entity={post} key={post.id} />
						))}
					</div>
					<div className="px-6 py-4 border-y-2 dark:border-gray-700">
						{posts.map(post => (
							<Post entity={post} key={post.id} />
						))}
					</div>
					<div className="flex flex-col gap-y-4 px-6">
						{descendants.map(post => (
							<PostWithChildren post={post} key={post.id} />
						))}
					</div>
				</div>
			) : (
				<div className="flex overflow-y-auto flex-col gap-y-4 px-6 py-4 w-full h-full no-scroll">
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
				</div>
			)}
		</>
	);
};

function PostWithChildren({ post }) {
	return (
		<>
			{post.children.length > 0 ? (
				<>
					<Post entity={post} />
					<div className="flex flex-col gap-y-4 pl-2 border-l-4 dark:border-gray-500">
						{post.children.map(postChild => (
							<PostWithChildren post={postChild} key={postChild.id} />
						))}
					</div>
				</>
			) : (
				<Post entity={post} />
			)}
		</>
	);
}

// src/components/feed/Conversation.vue
<script setup lang="ts">
import { onUnmounted, ref } from 'vue';
import { store } from '../../utils/store';
import Status, { PostType } from '../status/Status.vue';
import DummyStatus from '../status/DummyStatus.vue';
import { IconX } from '@tabler/icons-vue';
import ConversationChildPost from '../status/ConversationChildPost.vue';

const props = withDefaults(defineProps<{
	id: string,
	title?: boolean,
	closeButton?: boolean,
	onClose?: () => void,
	type?: PostType
}>(), {
	title: true,
	onClose: () => { },
	closeButton: false,
	type: PostType.Normal
})

let ancestors = ref<Entity.Status[]>([]);
let post = ref<Entity.Status | null>(null);
let descendants = ref<Entity.Status[]>([]);

// Finds all the parent elements of a post in a list of statuses
function findParentElements(array: Entity.Status[], elementId: string) {
	const parentElements = [];
	let currentElement = array.find(
		element => element.id === elementId
	);

	while (currentElement && currentElement.in_reply_to_id !== "") {
		parentElements.push(currentElement);
		currentElement = array.find(
			element => element.id === currentElement?.in_reply_to_id
		);
	}
	return parentElements;
}

store.client?.getStatus(props.id).then(res => {
	post.value = res.data;

	store.client?.getStatusContext(props.id).then(res => {
		if (!post.value) return;

		ancestors.value = findParentElements([...res.data.ancestors, post.value], post.value.id).reverse().slice(0, -1); // Slice because it includes the post, so remove last element
		descendants.value = res.data.descendants;
	})
});

onUnmounted(() => {
	post.value = null;
	ancestors.value = [];
	descendants.value = [];
})
</script>

<template>
	<div class="flex justify-between px-5 py-4" v-if="title">
		<h3 class="text-xl font-bold dark:text-gray-50">
			Conversation
		</h3>
		<button class="flex items-center justify-center" @click="onClose" title="Close conversation">
			<IconX v-if="closeButton" class="w-5 h-5 dark:text-gray-50" />
		</button>
	</div>

	<div v-if="post" class="flex overflow-y-scroll flex-col gap-y-5 py-4 w-full h-full no-scroll">
		<div class="flex flex-col gap-y-4 px-6">
			<Status :type="type" v-for="ancestor of ancestors" :status="ancestor" :interaction="true" />
		</div>
		<div
			class="px-6 py-4 border-y-2 dark:border-gray-700 bg-gray-300/10">
			<Status :type="type" :interaction="true" :status="post" />
		</div>
		<div class="flex flex-col gap-y-4 pr-6 pl-4 mb-20">
			<ConversationChildPost :key="JSON.stringify(descendants)" :posts="descendants" :mode="PostType.Normal" :parentId="post.id" />
		</div>
	</div>

	<div v-else class="flex overflow-y-auto flex-col gap-y-4 px-6 py-4 w-full h-full no-scroll">
		<DummyStatus />
		<DummyStatus />
		<DummyStatus />
		<DummyStatus />
		<DummyStatus />
		<DummyStatus />
	</div>
</template>
