// src/components/feed/Feed.vue
<script lang="ts">
export enum FeedType {
	Home,
	User,
	Notifications,
	Local
}
</script>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { store } from '../../utils/store';
import DummyStatus from '../status/DummyStatus.vue';
import Post from './Post.vue';
import Notification from '../notifications/Notification.vue';
import { IconHandStop } from '@tabler/icons-vue';

const props = withDefaults(defineProps<{
	type: FeedType,
	mode?: string,
	id?: string,
}>(), {
	mode: "all",
	id: "",
});

const entities = ref([]);


const DEFAULT_LOAD = 20;
const loading = ref(false);
const reachedEnd = ref<boolean>(false);

const interval = window.setInterval(async () => {
	const latestEntities = await getNewEntities((entities.value[0] as any).id)
	entities.value = [
		...latestEntities,
		...entities.value
	] as any
}, 15000)

const getNewEntities = async (since_id: string) => {
	if (loading.value) return;
	loading.value = true;
	let res;
	switch (props.type) {
		case FeedType.Home: {
			res = (await store.client?.getHomeTimeline({
				limit: DEFAULT_LOAD,
				since_id: since_id,
			})) as any;
			break;
		}
		case FeedType.User: {
			if (!props.id)
				throw Error(
					"Feed needs a user ID to work in user mode!"
				);
			res = (await store.client?.getAccountStatuses(props.id, {
				limit: DEFAULT_LOAD,
				since_id: since_id,
			})) as any;
			break;
		}

		case FeedType.Notifications: {
			res = (await store.client?.getNotifications({
				limit: DEFAULT_LOAD,
				since_id: since_id,
			})) as any;
			break;
		}

		case FeedType.Local: {
			res = (await store.client?.getLocalTimeline({
				limit: DEFAULT_LOAD,
				since_id: since_id,
			})) as any;
			break;
		}
	}
	loading.value = false;
	return res.data;
}

const getMoreEntities = async (before_id: string) => {
	let res;
	loading.value = true;

	switch (props.type) {
		case FeedType.Home: {
			res = (await store.client?.getHomeTimeline({
				limit: DEFAULT_LOAD,
				max_id: before_id,
			})) as any;
			break;
		}
		case FeedType.User: {
			if (!props.id)
				throw Error(
					"Feed needs a user ID to work in user mode!"
				);
			res = (await store.client?.getAccountStatuses(props.id, {
				limit: DEFAULT_LOAD,
				max_id: before_id,
			})) as any;
			break;
		}
		case FeedType.Notifications: {
			res = (await store.client?.getNotifications({
				limit: DEFAULT_LOAD,
				max_id: before_id,
			})) as any;
			break;
		}
		case FeedType.Local: {
			res = (await store.client?.getLocalTimeline({
				limit: DEFAULT_LOAD,
				max_id: before_id,
			})) as any;
			break;
		}
	}

	if (res.data.length === 0) reachedEnd.value = true;

	loading.value = false;
	return res.data;
}

const loadMoreEntities = async () => {
	if (loading.value) return false;
	if (reachedEnd.value) return false;
	const before_id = (entities.value[entities.value.length - 1] as any).id;

	entities.value = [
		...entities.value,
		...await getMoreEntities(before_id)
	] as any
}

onMounted(async () => {
	entities.value = await getNewEntities("");
});

onUnmounted(() => {
	window.clearInterval(interval);
})
</script>

<template>
	<template v-if="entities.length > 0 && type === FeedType.Home" v-for="entity of entities" :key="entity.id">
		<Post :status="entity" :interaction="true" />
	</template>
	<template v-if="entities.length > 0 && type === FeedType.User" v-for="entity of entities" :key="entity.id">
		<Post :status="entity" :interaction="true" />
	</template>
	<template v-if="entities.length > 0 && type === FeedType.Notifications" v-for="entity of entities.filter(e => {
		switch (props.mode) {
			case 'all':
				return true;
			case 'reblogs':
				return (
					(e as Entity.Notification).type === 'reblog'
				);
			case 'mention':
				return (
					(e as Entity.Notification).type ===
					'mention'
				);
			case 'favourites':
				return (
					(e as Entity.Notification).type ===
					'favourite'
				);
		}
	})" :key="entity.id">
		<Notification :notification="entity" />
	</template>
	<DummyStatus v-if="!loading && !reachedEnd" v-is-visible="loadMoreEntities"/>
	<DummyStatus v-if="!reachedEnd" />
	<DummyStatus v-if="!reachedEnd" />
	<DummyStatus v-if="!reachedEnd" />
	<DummyStatus v-if="!reachedEnd" />
	<DummyStatus v-if="!reachedEnd" />
	<div v-if="reachedEnd" class="flex justify-center">
		<div class="mx-4 flex flex-col dark:text-gray-300 items-center gap-y-3">
			<IconHandStop class="w-10 h-10" />
			<span>No more posts!</span>
			<span>You've reached the end of this timeline</span>
		</div>
	</div>
</template>

// src/components/feed/Feed.tsx
import { AuthContext } from "components/context/AuthContext";
import DummyStatus from "components/posts/DummyStatus";
import { Response } from "megalodon";
import { dedupeById } from "utils/functions";
import { useIsVisible } from "react-is-visible";
import { useState, useRef, useContext, useCallback, useEffect, MutableRef } from "preact/hooks";
import { memo } from "preact/compat";
import { StatusType } from "components/posts/Status";

export enum FeedType {
	Home = "home",
	User = "user",
	Notifications = "notifications",
	Local = "local",
}

const DEFAULT_LOAD = 20;

interface FeedProps {
	type: FeedType;
	entityElement: any;
	onChange: (entities: any) => void;
	options?: {
		id: string;
		filter?: string;
	};
	onLoadStart?: () => void;
	onLoadEnd?: () => void;
}

function Feed<T>(props: FeedProps) {
	const [entities, setEntities] = useState<T[]>([]);
	const entitiesRef = useRef<T[]>([]);
	const client = useContext(AuthContext);
	const loading = useRef<boolean>(false);
	const loadNewRef = useRef(null);
	const doLoadNewEntities = useIsVisible(loadNewRef);
	const [, setInitialLoadDone] = useState<boolean>(false);

	const getNewEntities = useCallback(
		async (since_id: string) => {
			if (loading.current) return;
			loading.current = true;
			props.onLoadStart && props.onLoadStart();
			let res: Response<T[]>;
			switch (props.type) {
			case FeedType.Home: {
				res = (await client?.getHomeTimeline({
					limit: DEFAULT_LOAD,
					since_id: since_id,
				})) as any;
				break;
			}
			case FeedType.User: {
				if (!props.options?.id)
					throw Error("Feed needs a user ID to work in user mode!");
				res = (await client?.getAccountStatuses(props.options.id, {
					limit: DEFAULT_LOAD,
					since_id: since_id,
				})) as any;
				break;
			}
			case FeedType.Notifications: {
				res = (await client?.getNotifications({
					limit: DEFAULT_LOAD,
					since_id: since_id,
				})) as any;
				break;
			}
			case FeedType.Local: {
				res = (await client?.getLocalTimeline({
					limit: DEFAULT_LOAD,
					since_id: since_id,
				})) as any;
				break;
			}
			}
			loading.current = false;
			props.onLoadEnd && props.onLoadEnd();
			return dedupeById(res.data as any) as T[];
		},
		[client, props.options?.id, props.type],
	);

	const loadEntitiesBefore = useCallback(
		async (before_id: string) => {
			if (loading.current) return [];
			loading.current = true;
			props.onLoadStart && props.onLoadStart();
			let res: Response<T[]>;
			switch (props.type) {
			case FeedType.Home: {
				res = (await client?.getHomeTimeline({
					limit: DEFAULT_LOAD,
					max_id: before_id,
				})) as any;
				break;
			}
			case FeedType.User: {
				if (!props.options?.id)
					throw Error("Feed needs a user ID to work in user mode!");
				res = (await client?.getAccountStatuses(props.options.id, {
					limit: DEFAULT_LOAD,
					max_id: before_id,
				})) as any;
				break;
			}
			case FeedType.Notifications: {
				res = (await client?.getNotifications({
					limit: DEFAULT_LOAD,
					max_id: before_id,
				})) as any;
				break;
			}
			case FeedType.Local: {
				res = (await client?.getLocalTimeline({
					limit: DEFAULT_LOAD,
					max_id: before_id,
				})) as any;
				break;
			}
			}
			loading.current = false;
			props.onLoadEnd && props.onLoadEnd();
			return dedupeById(res.data as any) as T[];
		},
		[client, props.options?.id, props.type],
	);

	useEffect(() => {
		const timeout = setTimeout(() => {
			async function fetchInitialData() {
				if (!loading.current) {
					const latestEntities = await getNewEntities("") ?? [];

					entitiesRef.current = dedupeById(latestEntities as any) as T[];

					props.onChange(latestEntities);
					setEntities(entitiesRef.current);
					setInitialLoadDone(true);
				}
			}

			fetchInitialData();
		}, 300);

		return () => clearTimeout(timeout);
	}, [client, getNewEntities]);

	useEffect(() => {
		const interval = window.setInterval(async () => {
			if (!loading.current) {
				const latestEntities = await getNewEntities((entitiesRef.current[0] as any).id) ?? [];

				entitiesRef.current = dedupeById([
					...latestEntities,
					...entitiesRef.current,
				] as any) as T[];
				props.onChange(latestEntities);
				setEntities(entitiesRef.current);
			}
		}, 15000);

		return () => window.clearInterval(interval);
	}, [getNewEntities]);

	useEffect(() => {
		async function loadMoreEntities() {
			if (doLoadNewEntities && !loading.current && entitiesRef.current.length > 0) {
				const latestPosts = await loadEntitiesBefore(
					(entitiesRef.current[entitiesRef.current.length - 1] as any).id,
				);

				entitiesRef.current = dedupeById([
					...entitiesRef.current,
					...latestPosts,
				] as any) as T[];
				props.onChange(latestPosts);
				setEntities(entitiesRef.current);
			}
		}

		loadMoreEntities();
	}, [doLoadNewEntities, loadEntitiesBefore]);

	return (
		<>
			{props.type !== FeedType.Notifications &&
				entities.map((entity: any) => (
					<props.entityElement key={entity.id} entity={entity} />
				))}

			{props.type === FeedType.Notifications &&
				entities
					.filter(e => {
						switch (props.options?.filter) {
						case "all":
							return true;
						case "reblogs":
							return (e as Entity.Notification).type === "reblog";
						case "mention":
							return (e as Entity.Notification).type === "mention";
						case "favourites":
							return (e as Entity.Notification).type === "favourite";
						}
					})
					.map((entity: any) => (
						<props.entityElement key={entity.id} entity={entity} />
					))}
			{(props.type === FeedType.Home || props.type === FeedType.User) && (
				<>
					<DummyStatus type="post" reference={loadNewRef} />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
					<DummyStatus type="post" />
				</>
			)}
			{props.type === FeedType.Notifications && (
				<>
					<DummyNotification reference={loadNewRef} />
					<DummyNotification />
					<DummyNotification />
					<DummyNotification />
					<DummyNotification />
					<DummyNotification />
					<DummyNotification />
				</>
			)}
		</>
	);
}

const DummyNotification = ({ reference }: { reference?: MutableRef<any> | null }) => {
	return (
		<>
			<li
				ref={reference ?? undefined}
				className={"flex flex-col gap-y-2 p-2 max-w-full rounded"}>
				<DummyStatus type={StatusType.Notification} />
			</li>
		</>
	);
};

export default memo(Feed);
