// src/components/Nav.vue
<script lang="ts" setup>
import { IconSun, IconSettings, IconPlus, IconHome, IconUsers, IconWorld } from "@tabler/icons-vue";
import NavElement, { NavigationItem } from "./NavElement.vue";
import { store } from "../utils/store";
import { IconMoon } from "@tabler/icons-vue";
import Link from "./transitions/Link.vue";

const navigation: NavigationItem[] = [
	{
		name: "Home",
		icon: IconHome,
		href: "/",
		type: "",
	},
	{
		name: "Instance",
		icon: IconUsers,
		href: "/local",
		type: "local",
	},
	{
		name: "Federated",
		icon: IconWorld,
		href: "/federated",
		type: "federated",
	},
];

const toggleTheme = () => {
	if (store.theme === "dark") {
		store.theme = "light"

		document.getElementsByTagName("html")[0].classList.remove("dark");
	} else if (store.theme === "light") {
		store.theme = "dark"

		document.getElementsByTagName("html")[0].classList.add("dark");
	}
}
</script>

<template>
	<div
		class="hidden h-full dark:bg-dark-800 bg-white flex-col bg-gradient-to-b border-r dark:border-gray-700 bg-light dark:dark:bg-dark-800 lg:flex">
		<div class="flex overflow-y-auto flex-col flex-1 items-center pt-5 pb-4">
			<Link href="/" class="flex flex-shrink-0 justify-center items-center px-2">
				<img :src="store.auth.instance?.thumbnail ?? ''" class="w-8 h-8 rounded" alt="" />
				<span class="sr-only">{{ store.auth.instance?.title }}</span>
			</Link>
			<nav class="flex-1 px-2 mt-5 space-y-1" aria-label="Sidebar" >
				<div v-for="nav in navigation" :key="nav.name">
					<NavElement :element="nav" />
				</div>
			</nav>
			<button
				title="Toggle light/dark mode"
				@click="toggleTheme"
				class="flex justify-center items-center p-2 mb-3 text-sm font-medium rounded-md duration-200 dark:text-gray-300 hover:bg-gray-300/40 hover:dark:bg-gray-700/40 hover:bg-opacity-75 group">
				<IconSun class="w-5 h-5" aria-hidden="true" v-if="store.theme === 'light'" />
				<IconMoon class="w-5 h-5" aria-hidden="true" v-if="store.theme === 'dark'" />
			</button>
			<button
				title="Open settings"
				class="flex justify-center items-center p-2 mb-3 text-sm font-medium rounded-md duration-200 dark:text-gray-300 hover:bg-gray-300/40 hover:dark:bg-gray-700/40 hover:bg-opacity-75 group">
				<IconSettings class="w-5 h-5" aria-hidden="true" />
			</button>
			<button title="Compose new post"
				@click="() => store.state.composer = true"
				class="flex justify-center items-center p-2 mb-3 text-sm font-medium rounded-md duration-200 dark:text-gray-300 bg-orange-300/20 hover:bg-orange-300/40 hover:bg-opacity-75 group">
				<IconPlus class="w-5 h-5" aria-hidden="true" />
				<span class="sr-only">Compose new post</span>
			</button>
			<Link :href="`/users/${store.auth.data?.id}`" class="flex justify-center items-center">
				<img :src="store.auth.data?.avatar ?? ''" class="w-9 h-9 rounded border dark:border-gray-700" alt="" />
				<span class="sr-only">
					Your avatar, click to visit your profile
				</span>
			</Link>
		</div>
	</div>
</template>

// components/sidebar/Nav.tsx
/* eslint-disable @next/next/no-img-element */
import { Transition } from "@headlessui/react";
import { IconHome, IconMoon, IconSun, IconUsers, IconWorld } from "@tabler/icons-react";
import { AuthContext } from "components/context/AuthContext";
import { StateContext } from "components/context/StateContext";
import { getCookie, setCookie } from "cookies-next";
import Link from "next/link";
import { Fragment, useContext, useEffect, useState } from "react";
import toast from "react-hot-toast";
import { classNames } from "utils/functions";

type NavigationItem = {
	name: string;
	icon: any;
	href: string;
	type: string;
};

type NavElementProps = {
	item: NavigationItem;
};

type NavProps = {};

const navigation: NavigationItem[] = [
	{
		name: "Home",
		icon: IconHome,
		href: "/",
		type: "",
	},
	{
		name: "Instance",
		icon: IconUsers,
		href: "/local",
		type: "local",
	},
	{
		name: "Federated",
		icon: IconWorld,
		href: "/federated",
		type: "federated",
	},
];

export default function Nav(props: NavProps): JSX.Element {
	const client = useContext(AuthContext);
	const [state, setState]: any = useContext(StateContext);
	const [account, setAccount] = useState<Entity.Account | undefined>();
	const [instance, setInstance] = useState<Entity.Instance | undefined>();
	const [theme, setTheme] = useState<string>("light");

	const toggleTheme = () => {
		const html = document.getElementsByTagName("html")[0];
		const themeCookie = (getCookie("theme") ?? "light").toString();
		if (themeCookie === "dark") {
			setCookie("theme", "light");
			html.className = html.className.replaceAll("dark", "");
			setTheme("light");
		} else if (themeCookie === "light") {
			setCookie("theme", "dark");
			html.className = html.className + " dark";
			setTheme("dark");
		}
	};

	useEffect(() => {
		if (window) {
			client
				?.verifyAccountCredentials()
				.then(data => {
					setAccount(data.data);
				})
				.catch(e => {
					console.log(e);
					toast.error("Couldn't load account data :(");
				});

			if (localStorage.getItem("instanceData")) {
				setInstance(JSON.parse(localStorage.getItem("instanceData")));
			} else {
				client?.getInstance().then(data => {
					// Caches instance data
					localStorage.setItem("instanceData", JSON.stringify(data.data));
					setInstance(data.data);
				});
			}

			setTheme((getCookie("theme") ?? "light").toString());
		}
	}, [client]);

	return (
		<div className="hidden fixed top-0 bottom-0 left-0 z-50 flex-col flex-1 col-span-1 min-h-0 bg-gradient-to-b border-r dark:border-gray-700 bg-light dark:bg-dark lg:flex">
			<div className="flex overflow-y-auto flex-col flex-1 items-center pt-5 pb-4">
				<Link
					href="/"
					onClick={e => {
						e.preventDefault();
						setState(s => ({
							...s,
							path: "/"
						}));
						history.pushState(null, null, "/");
					}}
					className="flex flex-shrink-0 justify-center items-center px-2">
					<img src={instance?.thumbnail} className="w-8 h-8 rounded" alt="" />
				</Link>
				<nav className="flex-1 px-2 mt-5 space-y-1" aria-label="Sidebar">
					{navigation.map(item => (
						<NavElement item={item} key={item.name} />
					))}
				</nav>
				<button
					onClick={e => {
						e.preventDefault();
						toggleTheme();
					}}
					className="flex justify-center items-center p-2 mb-3 text-sm font-medium rounded-md duration-200 dark:text-gray-300 hover:bg-gray-300/40 hover:dark:bg-gray-700/40 hover:bg-opacity-75 group">
					{theme === "light" && (
						<>
							<IconSun className="w-5 h-5" aria-hidden={true} />
							<span className="sr-only">Enable dark mode</span>
						</>
					)}
					{theme === "dark" && (
						<>
							<IconMoon className="w-5 h-5" aria-hidden={true} />
							<span className="sr-only">Enable light mode</span>
						</>
					)}
				</button>
				<Link href={`/users/${account?.id}`} className="flex justify-center items-center">
					<img
						src={account?.avatar}
						className="w-9 h-9 rounded border dark:border-gray-700"
						alt=""
					/>
				</Link>
			</div>
		</div>
	);
}

export function MobileNav(props: NavProps): JSX.Element {
	const client = useContext(AuthContext);
	const [state, setState]: any = useContext(StateContext);
	const [account, setAccount] = useState<Entity.Account | undefined>();
	const [instance, setInstance] = useState<Entity.Instance | undefined>();
	const [theme, setTheme] = useState<string>("light");

	const toggleTheme = () => {
		const html = document.getElementsByTagName("html")[0];
		const themeCookie = (getCookie("theme") ?? "light").toString();
		if (themeCookie === "dark") {
			setCookie("theme", "light");
			html.className = html.className.replaceAll("dark", "");
			setTheme("light");
		} else if (themeCookie === "light") {
			setCookie("theme", "dark");
			html.className = html.className + " dark";
			setTheme("dark");
		}
	};

	useEffect(() => {
		if (window) {
			client
				?.verifyAccountCredentials()
				.then(data => {
					setAccount(data.data);
				})
				.catch(e => {
					console.log(e);
					toast.error("Couldn't load account data :(");
				});

			if (localStorage.getItem("instanceData")) {
				setInstance(JSON.parse(localStorage.getItem("instanceData")));
			} else {
				client?.getInstance().then(data => {
					// Caches instance data
					localStorage.setItem("instanceData", JSON.stringify(data.data));
					setInstance(data.data);
				});
			}

			setTheme((getCookie("theme") ?? "light").toString());
		}
	}, [client]);

	return (
		<div className="flex z-50 flex-col min-h-0 dark:border-gray-700 bg-light bg-dark">
			<div className="flex overflow-y-auto flex-col flex-1 text-gray-800 dark:text-gray-100">
				<Link
					href="/"
					onClick={e => {
						e.preventDefault();
						setState(s => ({
							...s,
							path: "/",
						}));
						history.pushState(null, null, "/");
					}}
					className="flex flex-shrink-0 gap-x-4 items-center text-lg font-poppins">
					<img src={instance?.thumbnail} className="w-12 h-12 rounded" alt="" />
					{instance?.title}
				</Link>
				<nav className="flex-1 mt-5 space-y-1" aria-label="Sidebar">
					{navigation.map(item => (
						<NavElementMobile item={item} key={item.name} />
					))}
				</nav>
				<button
					onClick={e => {
						e.preventDefault();
						toggleTheme();
					}}
					className="flex gap-x-4 items-center p-2 mb-3 text-lg font-medium bg-opacity-75 rounded-md duration-200 dark:text-gray-300 bg-gray-300/40 dark:bg-gray-700/40 group">
					{theme === "light" && (
						<>
							<IconSun className="w-5 h-5" aria-hidden={true} />
							<span>Enable dark mode</span>
						</>
					)}
					{theme === "dark" && (
						<>
							<IconMoon className="w-5 h-5" aria-hidden={true} />
							<span>Enable light mode</span>
						</>
					)}
				</button>
				<Link href={`/users/${account?.id}`} className="flex items-center">
					<img
						src={account?.avatar}
						className="w-9 h-9 rounded border dark:border-gray-700"
						alt=""
					/>
				</Link>
			</div>
		</div>
	);
}

function NavElementMobile(props: NavElementProps) {
	const [current, setCurrent] = useState<boolean>(false);
	const [state, setState] = useContext(StateContext);

	useEffect(() => {
		setCurrent(
			typeof window !== "undefined" ? window.location.pathname === props.item.href : false,
		);
	}, [props.item.href]);

	return (
		<div className="flex flex-row items-center">
			<Link
				href={props.item.href}
				onClick={e => {
					if (!e.ctrlKey && !e.metaKey) {
						e.preventDefault();
						setState(s => ({
							...s,
							path: props.item.href,
						}));
						history.pushState(null, null, props.item.href);
					}
				}}
				className={classNames(
					current
						? "bg-gray-300/40 dark:bg-gray-700/40"
						: "hover:bg-gray-300/40 hover:dark:bg-gray-700/40 hover:bg-opacity-75",
					"flex gap-x-4 justify-center items-center p-2 text-lg font-medium rounded-md duration-200 font-poppins group",
				)}>
				<props.item.icon
					className="flex-shrink-0 w-5 h-5 text-gray-600 dark:text-gray-300"
					aria-hidden="true"
				/>
				{props.item.name}
			</Link>
		</div>
	);
}

function NavElement(props: NavElementProps) {
	const [current, setCurrent] = useState<boolean>(false);
	const [state, setState] = useContext(StateContext);
	let [showTooltip, setShowTooltip] = useState<boolean>(false);

	useEffect(() => {
		setCurrent(typeof window !== "undefined" ? window.location.pathname === props.item.href : false);
	}, [props.item.href]);

	return (
		<div className="flex flex-row items-center">
			<Link
				href={props.item.href}
				onClick={e => {
					if (!e.ctrlKey && !e.metaKey) {
						e.preventDefault();
						setState(s => ({
							...s,
							path: props.item.href
						}));
						history.pushState(null, null, props.item.href);
					}
				}}
				className={classNames(
					current
						? "bg-gray-300/40 dark:bg-gray-700/40"
						: "hover:bg-gray-300/40 hover:dark:bg-gray-700/40 hover:bg-opacity-75",
					"flex justify-center items-center p-2 mx-2 text-sm font-medium rounded-md duration-200 group",
				)}
				onMouseEnter={() => {
					setShowTooltip(true);
				}}
				onMouseLeave={() => {
					setShowTooltip(false);
				}}>
				<props.item.icon
					className="flex-shrink-0 w-5 h-5 text-gray-600 dark:text-gray-300"
					aria-hidden="true"
				/>
			</Link>
			<Transition
				as={Fragment}
				show={showTooltip}
				enter="transform transition duration-150"
				enterFrom="opacity-0 scale-50"
				enterTo="opacity-100 scale-100"
				leave="transform duration-150 transition ease-in-out"
				leaveFrom="opacity-100 scale-100"
				leaveTo="opacity-0 scale-95">
				<div
					role="tooltip"
					className="inline-block absolute z-10 px-3 py-2 ml-14 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 shadow-sm dark:text-gray-100 bg-dark dark:border-gray-700 font-inter">
					{props.item.name}
				</div>
			</Transition>
		</div>
	);
}
