// components/status/InteractionBar.vue
<script setup lang="ts">
import { IconStar, IconRocket, IconMoodHappy, IconQuote, IconLock, IconStarFilled, IconMessage, IconPin, IconEdit, IconForbid, IconCheck, IconDots, IconCopy, IconLink } from "@tabler/icons-vue";
import { Entity } from "megalodon";
import { store } from "../../utils/store";
import { Dialog, DialogPanel, Menu, MenuButton, MenuItem, MenuItems, TransitionRoot } from "@headlessui/vue";
import ScaleFadeSlide from "../transitions/ScaleFadeSlide.vue";
import { NotificationType, addNotification } from "../snackbar/Snackbar.vue";
import { ref } from "vue";
import { IconPinFilled } from "@tabler/icons-vue";
import Input from "../input/Input.vue";

const props = defineProps<{
	status: Entity.Status;
}>();

const _status = ref<Entity.Status>(props.status);
const reacting = ref<boolean>(false);
const reactionFilter = ref<Entity.Emoji[]>(store.emojis);

const toggleFavourite = async () => {
	if (_status.value.favourited) {
		_status.value.favourited = false;
		store.client?.unfavouriteStatus(_status.value.id);
	} else {
		_status.value.favourited = true;
		store.client?.favouriteStatus(_status.value.id);
	}
};

const toggleReblog = () => {
	if (_status.value.reblogged) {
		_status.value.reblogged = false;
		store.client?.unreblogStatus(_status.value.id);
	} else {
		_status.value.reblogged = true;
		store.client?.reblogStatus(_status.value.id);
	}
};

const block = () => {
	store.client?.blockAccount(_status.value.account.id).then(res => {
		addNotification("Blocked account!", NotificationType.Normal, IconCheck);
	})
}

const togglePin = () => {
	if (_status.value.pinned) {
		store.client?.unpinStatus(_status.value.id).then(res => {
			addNotification("Unpinned status!", NotificationType.Normal, IconPin);
		});
	} else {
		store.client?.pinStatus(_status.value.id).then(res => {
			addNotification("Pinned status!", NotificationType.Normal, IconPinFilled);
		});
	}
}

const toggleReaction = () => {
	if (store.auth.type === "mastodon") return addNotification("Mastodon does not support reactions!");
	reacting.value = !reacting.value;
}

const filterReactions = (event: Event) => {
	reactionFilter.value = store.emojis.filter(e => e.shortcode.includes((event.target as HTMLInputElement).value)) ;
}

const react = (emoji: Entity.Emoji) => {
	store.client?.createEmojiReaction(_status.value.id, emoji.shortcode).then(res => {
		_status.value = res.data;
		addNotification("Added reaction!", NotificationType.Normal, IconMoodHappy);
		reacting.value = false;
	})
}

const edit = () => {
	store.editing = _status.value;
}

const copyUrl = () => {
	navigator.clipboard.writeText(_status.value.url);
}
</script>

<style scoped lang="postcss">
.menu-item {
	@apply text-gray-700 duration-300 w-full dark:text-gray-50 hover:bg-orange-200 rounded-lg text-sm dark:hover:bg-orange-700/20 flex flex-row items-center py-2;
}

.menu-icon {
	@apply mx-2 h-[1.2em] w-[1.2em] mb-0.5;
}

.button {
	@apply gap-x-2 flex justify-center static hover:animate-hithere border-none focus:outline-none outline-none shadow-none px-0
}
</style>

<template>
	<div
		class="flex justify-between mt-3 w-full text-gray-700 dark:text-gray-400 px-4">
		<button
			class="button"
			@click="
				() => {
					store.replyingTo = _status;
					store.quotingTo = null;
					store.state.composer = true;
				}
			"
			title="Reply to this post">
			<IconMessage aria-hidden="true" class="w-5 h-5" />
			{{ _status.replies_count > 0 ? _status.replies_count : "" }}
		</button>
		<button
			class="button"
			@click="toggleFavourite"
			title="Favourite this post">
			<IconStarFilled
				v-if="_status.favourited"
				aria-hidden="true"
				class="w-5 h-5 text-yellow-400 animate-[spin_1s_ease-in-out]" />
			<IconStar v-else aria-hidden="true" class="w-5 h-5" />
			{{ _status.favourites_count > 0 ? _status.favourites_count : "" }}
		</button>
		<button @click="toggleReblog" title="Boost this post" class="button">
			<template
				v-if="
					_status.visibility !== 'private' &&
					_status.visibility !== 'direct'
				">
				<IconRocket
					v-if="_status.reblogged"
					aria-hidden="true"
					class="w-5 h-5 text-green-400 animate-[spin_1s_ease-in-out]" />
				<IconRocket v-else aria-hidden="true" class="w-5 h-5" />
				{{ _status.reblogs_count > 0 ? _status.reblogs_count : "" }}
			</template>
			<template v-else>
				<IconLock aria-hidden="true" class="w-5 h-5 text-gray-300" />
			</template>
		</button>
		<button class="button" title="Add reaction" @click="toggleReaction">
			<IconMoodHappy aria-hidden="true" class="w-5 h-5" />

			<TransitionRoot appear :show="reacting">
			<Dialog @close="() => reacting = false" class="z-50 fixed bottom-0">
				<ScaleFadeSlide>
					<DialogPanel>
						<div class="w-80 flex flex-col bottom-0 left-0 m-4 p-3 absolute z-50 bg-orange-100/50 backdrop-blur-md dark:bg-dark-800/75 border dark:border-gray-700 shadow rounded-xl h-72">
							<Input @input="filterReactions" :icon="IconMoodHappy" class="dark:border-gray-700" placeholder="Search for emoji here" name="emoji" />
							<div className="grid grid-cols-6 justify-around no-scroll p-3 gap-4 overflow-scroll">
								<button @click="() => react(emoji)" v-for="emoji of reactionFilter" :key="emoji.url" title={emoji.shortcode} class="flex items-center justify-center w-full">
									<img :src="emoji.url" className="w-7 h-7 rounded" />
								</button>
							</div>
						</div>
					</DialogPanel>
				</ScaleFadeSlide>
			</Dialog>
			</TransitionRoot>
		</button>
		<button
			class="button"
			@click="
				e => {
					store.quotingTo = _status;
					store.replyingTo = null;
					store.state.composer = true;
				}
			"
			title="Quote this post">
			<IconQuote aria-hidden="true" class="w-5 h-5" />
		</button>
		<Menu as="button" class="relative">
			<MenuButton>
				<div
					class="button hover:!animate-none"
					title="Quote this post">
					<IconDots aria-hidden="true" class="w-5 h-5" />
				</div>
			</MenuButton>

			<ScaleFadeSlide>
				<MenuItems
					:unmount="true"
					class="p-1.5 gap-x-4 origin-top-right outline-none text-base absolute right-0 w-44 overflow-hidden sm:text-sm rounded-xl shadow-lg bg-white/80 dark:bg-dark-700 backdrop-blur-lg focus:outline-none">
					<MenuItem
						v-if="_status.account.id === store.auth.data?.id"
						as="button"
						class="menu-item">
						<IconEdit
							class="menu-icon"
							aria-hidden="true" />
						Edit
					</MenuItem>
					<MenuItem
						@click="copyUrl"
						as="button"
						class="menu-item">
						<IconLink
							class="menu-icon"
							aria-hidden="true" />
						Copy link
					</MenuItem>
					<MenuItem
						v-if="(_status.account.id === store.auth.data?.id) && !_status.pinned"
						@click="togglePin"
						as="button"
						class="menu-item">
						<IconPin
							class="menu-icon"
							aria-hidden="true" />
						Pin
					</MenuItem>
					<MenuItem
						v-if="(_status.account.id === store.auth.data?.id) && _status.pinned"
						@click="togglePin"
						as="button"
						class="menu-item">
						<IconPinFilled
							class="menu-icon"
							aria-hidden="true" />
						Unpin
					</MenuItem>
					<MenuItem
						v-if="_status.account.id !== store.auth.data?.id"
						@click="block"
						as="button"
						class="menu-item">
						<IconForbid
							class="menu-icon"
							aria-hidden="true" />
						Block
					</MenuItem>
				</MenuItems>
			</ScaleFadeSlide>
		</Menu>
	</div>
</template>

// src/components/posts/InteractionBar.tsx
import { Dialog, Transition } from "@headlessui/react";
import {
	IconDots,
	IconLock,
	IconMessage,
	IconMoodHappy,
	IconQuote,
	IconRocket,
	IconStar,
	IconStarFilled,
} from "@tabler/icons-preact";
import { AuthContext } from "components/context/AuthContext";
import { Input } from "components/forms/Input";
import { Entity } from "megalodon";
import { memo } from "preact/compat";
import { StateUpdater, useContext, useState } from "preact/hooks";
import { Fragment } from "preact/jsx-runtime";
import { JSXInternal } from "preact/src/jsx";
import { toast } from "react-hot-toast";
import { classNames } from "utils/functions";
import { useBackupStore } from "utils/useBackupStore";

/**
 * Small bar containing all the buttons on a post, such as "favourite", "quote", "reply"...
 * @returns
 */
function InteractionBar({
	status,
	setStatus,
}: {
	status: Entity.Status;
	setStatus: StateUpdater<Entity.Status>;
}) {
	const client = useContext(AuthContext);
	const [showEmojiPicker, setShowEmojiPicker] = useState<boolean>(false);

	const [emojiFilter, setEmojiFilter] = useState<string>("");

	const { store, setStore } = useBackupStore();

	return (
		<div className="flex justify-between px-5 mt-3 w-full text-gray-700 dark:text-gray-400">
			<InteractionBarIcon
				title="Reply to this post"
				onClick={() => {
					setStore(prev => ({
						...prev,
						replyingTo: status,
						quotingTo: null,
						postComposerOpened:
							window.innerWidth < 1400 ||
							store.viewingConversation !== "",
					}));
				}}>
				<IconMessage aria-hidden={true} className="w-5 h-5" />
				<span className="sr-only">Reply to this post</span>
			</InteractionBarIcon>

			<InteractionBarIcon
				title={
					status.favourited
						? "You favourited this post!"
						: "Favourite this post"
				}
				onClick={() => {
					if (status.favourited) {
						setStatus(prev => ({
							...prev,
							favourited: false,
						}));
						client?.unfavouriteStatus(status.id);
					} else if (!status.favourited) {
						setStatus(prev => ({
							...prev,
							favourited: true,
						}));
						client?.favouriteStatus(status.id);
					}
				}}>
				{status.favourited ? (
					<>
						<IconStarFilled
							aria-hidden={true}
							className="w-5 h-5 text-yellow-400 animate-[spin_1s_ease-in-out]"
						/>
					</>
				) : (
					<>
						<IconStar aria-hidden={true} className="w-5 h-5" />
					</>
				)}
			</InteractionBarIcon>

			<InteractionBarIcon
				title="Boost this post"
				onClick={() => {
					if (status.reblogged) {
						setStatus(prev => ({
							...prev,
							reblogged: false,
						}));
						client?.unreblogStatus(status.id);
					} else if (!status.reblogged) {
						setStatus(prev => ({
							...prev,
							reblogged: true,
						}));
						client?.reblogStatus(status.id);
					}
				}}>
				{status.visibility !== "private" &&
				status.visibility !== "direct" ? (
					<>
						{status.reblogged ? (
							<>
								<span className="sr-only">
									You boosted this post!
								</span>
								<IconRocket
									aria-hidden={true}
									className="w-5 h-5 text-green-400 animate-[spin_1s_ease-in-out]"
								/>
							</>
						) : (
							<>
								<span className="sr-only">Boost this post</span>
								<IconRocket
									aria-hidden={true}
									className="w-5 h-5"
								/>
							</>
						)}
					</>
				) : (
					<>
						<span className="sr-only">
							This post is locked and cannot be boosted
						</span>
						<IconLock
							aria-hidden={true}
							className="w-5 h-5 text-gray-300"
						/>
					</>
				)}
			</InteractionBarIcon>

			<InteractionBarIcon
				shake={false}
				title="Add reaction"
				onClick={() => {
					if (store.auth.type === "mastodon") return toast.error("Mastodon does not support reactions!");
					setShowEmojiPicker(true);
				}}>
				<>
					<IconMoodHappy className="w-5 h-5" aria-hidden={true} />
					<span className="sr-only">Add reaction</span>

					<Transition appear show={showEmojiPicker} as={Fragment}>
						<Dialog
							onClose={() => {
								setShowEmojiPicker(false);
							}}
							onClick={(e: any) => {
								e.stopPropagation();
							}}
							className="z-50 fixed bottom-0">
							<Transition.Child
								as={Fragment}
								enter="ease-out duration-100"
								enterFrom="opacity-0 scale-95"
								enterTo="opacity-100 scale-100"
								leave="ease-in duration-200"
								leaveFrom="opacity-100 scale-100"
								leaveTo="opacity-0 scale-95">
								<Dialog.Panel>
									<div className="w-80 flex flex-col bottom-0 left-0 m-4 p-3 absolute z-50 bg-orange-100/50 backdrop-blur-md dark:bg-dark-800/75 border dark:border-gray-700 shadow rounded-xl h-72">
										<Input autoFocus={true} onChange={e => {
											setEmojiFilter((e.target as HTMLInputElement).value);
										}} className="dark:border-gray-700" placeholder="Search for emoji here" isLoading={false} name="emoji">{""}</Input>
										<div className="grid grid-cols-6 justify-around no-scroll p-3 gap-4 overflow-scroll">
											{store.emojis.filter(e => e.shortcode.includes(emojiFilter)).map(emoji => (
												<button title={emoji.shortcode} className="flex items-center justify-center w-full" onClick={() => {
													client?.createEmojiReaction(status.id, emoji.shortcode).then(res => {
														setStatus(res.data);
														toast.success("Added reaction!");
														setShowEmojiPicker(false);
													}).catch(err => {
														console.log(err);
														toast.error("Error adding reaction");
													});
												}}>
													<img src={emoji.url} className="w-7 h-7 rounded" />
												</button>
											))}
										</div>
									</div>
								</Dialog.Panel>
							</Transition.Child>
						</Dialog>
					</Transition>
				</>
			</InteractionBarIcon>

			<InteractionBarIcon
				title="Quote this post"
				onClick={() => {
					if (store.auth.type === "mastodon")
						return toast.error(
							"Mastodon does not support quote posts!"
						);
					setStore(prev => ({
						...prev,
						quotingTo: status,
						replyingTo: null,
						postComposerOpened:
							window.innerWidth < 1400 ||
							store.viewingConversation !== "",
					}));
				}}>
				<IconQuote className="w-5 h-5" aria-hidden={true} />
				<span className="sr-only">Quote this post</span>
			</InteractionBarIcon>

			<InteractionBarIcon title="Open options menu (not implemented)">
				<IconDots className="w-5 h-5" />
				<span className="sr-only">
					Open options menu (not implemented)
				</span>
			</InteractionBarIcon>
		</div>
	);
}

export default memo(InteractionBar);

const InteractionBarIcon = memo(
	({
		children,
		onClick = () => {
			//
		},
		title = "",
		shake = true,
	}: {
		children: any;
		onClick?: (
			e: JSXInternal.TargetedMouseEvent<HTMLButtonElement>
		) => void;
		title: string;
		shake?: boolean;
	}) => {
		return (
			<button
				title={title}
				className={classNames(
					"flex justify-center !static",
					shake && "hover:animate-hithere"
				)}
				onClick={onClick}>
				{children}
			</button>
		);
	}
);
