// components/status/Status.vue
<script setup lang="ts">
import { Entity } from "megalodon";
import { onMounted, ref } from "vue";
import { classNames, withEmojis, fromNow } from "../../utils/functions";
import InteractionBar from "./InteractionBar.vue";
import Button from "../button/Button.vue";
import StatusAttachments from "./StatusAttachments.vue";
import Link from "../transitions/Link.vue";
import ReplyTo from "./ReplyTo.vue";
import Poll from "./Poll.vue";
import Reactions from "./Reactions.vue";
import { store } from "../../utils/store";

const props = defineProps<{
	status: Entity.Status;
	interaction: boolean;
	type: PostType;
}>();

const expand = ref<boolean>(false);
const clamps = ref<boolean>(true);
const show = ref<boolean>(false);
const textRef = ref<HTMLParagraphElement>();

onMounted(() => {
	if (textRef.value) {
		const lineHeight = parseInt(getComputedStyle(textRef.value).lineHeight);
		const overflowHeight = lineHeight * 6;
		const elementHeight = textRef.value.clientHeight;

		clamps.value = elementHeight > overflowHeight;
	}
});

const toggleExpand = () => {
	expand.value = !expand.value;
};

const toggleShow = () => {
	show.value = !show.value;
};
</script>

<script lang="ts">
export enum PostType {
	Normal,
	Small,
	Tiny
}
</script>

<template>
	<div class="flex flex-col max-w-full font-inter cursor-pointer">
		<div class="flex flex-col min-w-0 grow gap-y-1">
			<div v-if="type !== PostType.Tiny"
				class="flex flex-row overflow-hidden text-[0.95rem] text-ellipsis whitespace-nowrap w-full">
				<NuxtLink :to="`/user/${status.account.id}`" class="flex-shrink-0 mr-2"
					:title="`${status.account.display_name}'s profile'`">
					<img loading="lazy" alt="" :src="status.account.avatar" :class="[
						'bg-white overflow-hidden w-10 h-10 dark:bg-dark-800-800 rounded-lg	 border border-gray-300 dark:border-dark-700',
						type === PostType.Normal
							? 'md:w-12 md:h-12'
							: 'md:w-10 md:h-10',
					]" />
				</NuxtLink>
				<div :class="[
					'flex flex-col grow text-sm justify-around overflow-hidden text-ellipsis']">
				<div class="flex flex-row justify-between">
					<h4 class="font-bold dark:text-gray-200" :title="status.account.display_name" v-html="
					withEmojis(
						status.account.display_name,
						status.account.emojis
					)">
					</h4>
						<RouterLink :to="`/posts/${status.id}`"
							class="text-sm text-gray-700 dark:text-gray-300 hover:underline"
							v-html="fromNow(new Date(status.created_at))">
						</RouterLink>
					</div>
					<h5 :title="status.account.acct"
						class="overflow-hidden ml-0 text-gray-500 overflow-ellipsis dark:text-gray-400">
						@{{ status.account.acct }}
					</h5>
				</div>
			</div>
			<div v-else class="flex flex-row items-center gap-x-1 whitespace-nowrap overflow-hidden text-ellipsis">
				<img loading="lazy" alt="" :src="status.account.avatar" :class="[
					'bg-white overflow-hidden w-4 h-4 dark:bg-dark-800-800 rounded border border-gray-300 dark:border-dark-700',
				]" />
				<h4 class="font-bold dark:text-gray-200" :title="status.account.display_name" v-html="
				withEmojis(
					status.account.display_name,
					status.account.emojis
				)
					"></h4>
				<h5 :title="status.account.acct"
					class="overflow-hidden ml-0 text-gray-500 overflow-ellipsis dark:text-gray-400">
					@{{ status.account.acct.split("@")[0] }}
				</h5>

			</div>
			<div class="flex flex-col gap-y-1 text-sm">
				<ReplyTo v-if="status.in_reply_to_id" :status="status" />

				<div v-if="status.sensitive" class="flex gap-x-2 items-center font-bold dark:text-gray-100">
					{{
						status.spoiler_text === ""
						? "Marked as sensitive"
						: withEmojis(status.spoiler_text, status.emojis)
					}}

					<Button class="!py-1 !px-2" @click="toggleShow" theme="gray">
						{{ show ? "Hide" : "Show" }}
					</Button>
				</div>

				<p ref="textRef" v-html="withEmojis(status.content, status.emojis)" :class="
				classNames(
					'mt-1 status-text rounded text-sm duration-200 status-text dark:text-gray-50 break-words max-w-full',
					status.sensitive && !show && 'filter blur-lg',
					clamps && !expand && 'line-clamp-6'
				)
					"></p>

				<button v-if="clamps" @click="toggleExpand"
					class="mx-auto w-full text-sm text-blue-800 dark:text-blue-100 hover:underline">
					<template v-if="expand">Less</template>
					<template v-else="expand">More</template>
				</button>

				<Poll v-if="status.poll" :status="status" />

				<Reactions :status="status" v-if="status.emoji_reactions.length > 0" />

				<StatusAttachments :type="type" :status="status" v-if="status.media_attachments.length > 0" />
			</div>
		</div>

		<InteractionBar v-once v-if="props.interaction" :status="status" />
	</div>
</template>

// src/components/posts/Status.tsx
import { Entity } from "megalodon";
import { useRef, useState } from "preact/hooks";
import { classNames, fromNow, withEmojis } from "utils/functions";
import InteractionBar from "./InteractionBar";
import PostAttachments from "./PostAttachments";
import ReplyTo from "./ReplyTo";
import SensitiveTextSpoiler from "./SensitiveTextSpoiler";
import useLineClamp from "use-line-clamp";
import { StatusPoll } from "./StatusPoll";
import { Reactions } from "./Reaction";
import { Link } from "components/transitions/Link";
import { memo } from "preact/compat";

export enum StatusType {
	Notification = "notification",
	Post = "post",
}

interface StatusProps {
	status: Entity.Status;
	type: StatusType;
	showInteraction?: boolean;
}

function Status({
	status: statusProp,
	type,
	showInteraction = true,
}: StatusProps) {
	const [expand, setExpand] = useState(false);
	const [status, setStatus] = useState(statusProp);
	const [showText, setShowText] = useState(false);
	const textElementRef = useRef<HTMLParagraphElement>(null);
	const clamps = useLineClamp(textElementRef, {
		lines: 6,
	});

	const toggleExpand = () => {
		setExpand(prev => !prev);
	};

	return (
		<div className="flex flex-col max-w-full font-inter cursor-pointer">
			<div className="flex flex-col min-w-0 grow gap-y-1">
				<div className="flex flex-row overflow-hidden text-[0.95rem] text-ellipsis whitespace-nowrap w-full">
					<Link
						href={`/users/${status.account.id}`}
						className="flex-shrink-0 mr-2">
						<img
							loading="lazy"
							alt={`${status.account.acct}'s avatar`}
							src={status.account.avatar}
							className={`${
								type == StatusType.Post
									? "w-12 h-12"
									: "w-10 h-10"
							} bg-white overflow-hidden dark:dark:bg-dark-800-800 rounded border border-gray-300 dark:border-gray-700 `}
						/>
					</Link>
					<div
						className={classNames(
							"flex flex-col grow",
							type === StatusType.Notification && "text-sm"
						)}>
						<h4
							className="font-bold dark:text-gray-200"
							title={status.account.display_name}>
							{withEmojis(
								status.account.display_name,
								status.account.emojis
							)}
						</h4>
						<h5
							title={status.account.acct}
							className="overflow-hidden ml-0 text-gray-500 overflow-ellipsis dark:text-gray-400">
							@{status.account.acct}
						</h5>
					</div>
					<Link
						href={`/posts/${status.id}`}
						sidebar={status.id}
						className="text-sm text-gray-700 dark:text-gray-300 hover:underline">
						{fromNow(new Date(status.created_at))}
					</Link>
				</div>
				<div className="flex flex-col gap-y-1">
					{status.in_reply_to_id && <ReplyTo status={status} />}

					{status.sensitive && (
						<SensitiveTextSpoiler
							status={status}
							showText={showText}
							setShowText={setShowText}
						/>
					)}

					{/* Actual text */}

					<p
						ref={textElementRef}
						className={`mt-1 status-text rounded text-sm duration-200 status-text dark:text-gray-50 break-words w-full ${
							status.sensitive && !showText && "filter blur-lg"
						} ${clamps && !expand && "line-clamp-6"}`}>
						{withEmojis(status.content, status.emojis)}
					</p>

					{/* Show More / Show Less button */}
					{clamps && (
						<>
							<button
								className="mx-auto w-full text-sm text-blue-800 dark:text-blue-100 hover:underline"
								onClick={toggleExpand}>
								{expand === true ? "Less" : "More"}
							</button>
						</>
					)}

					{status.emoji_reactions && (
						<Reactions status={status} setStatus={setStatus} />
					)}

					{status.poll && (
						<StatusPoll status={status} setStatus={setStatus} />
					)}
				</div>
				{status.media_attachments.length > 0 && (
					<div className={"mt-2"}>
						<PostAttachments status={status} />
					</div>
				)}
			</div>

			{showInteraction && (
				<InteractionBar status={status} setStatus={setStatus} />
			)}
		</div>
	);
}

export default memo(Status);
