// components/buttons/Button.tsx
import Spinner from "components/spinners/Spinner";
import { DetailedHTMLProps, ButtonHTMLAttributes } from "react";
import { classNames } from "utils/functions";

const styles = {
	gray: "text-gray-700 bg-white bg-dark border-gray-300 outline-none hover:bg-gray-50 dark:border-gray-600 dark:text-gray-200",
	orange: "bg-orange-600 hover:bg-orange-700 text-white border-transparent",
	orangeLight: "text-orange-700 dark:text-orange-200 bg-orange-100 dark:bg-orange-800 hover:bg-orange-200 border-transparent",
};

interface ButtonProps {
	children: any;
	style?: any;
	isLoading?: boolean;
	spinnerClasses?: string;
	ringColor?: string;
	className?: string;
}

export default function Button({
	children,
	ringColor = "",
	className = "",
	style = "",
	isLoading = false,
	spinnerClasses = "h-4 text-gray-100 fill-orange-400",
	...props
}: ButtonProps & DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>) {
	return (
		<button
			{...props}
			className={classNames(
				"inline-flex  justify-center relative items-center px-4 py-2 text-base font-medium rounded-md border shadow-sm duration-200 font-inter focus:outline-none sm:text-sm",
				style && styles[style],
				className,
				isLoading && "!text-transparent",
				ringColor !== ""
					? `focus:ring-2 focus:ring-offset-2 focus:ring-${ringColor}`
					: "ring-0 focus:ring-0",
			)}>
			{isLoading && <Spinner className={`absolute w-auto ${spinnerClasses}`} />}
			{children}
		</button>
	);
}

// src/components/button/Button.vue
<script lang="ts">
import { defineComponent, PropType } from "vue";
import { classNames } from "../../utils/functions";

const themes: { [key: string]: string } = {
	gray: "dark:text-gray-200 bg-gray-100 text-black dark:bg-dark-800 dark:border-gray-600 outline-none hover:scale-105",
	orange: "bg-orange-600 hover:bg-orange-700 text-white border-transparent",
	orangeLight: "text-orange-700 dark:text-orange-200 bg-orange-100 dark:bg-orange-800 hover:bg-orange-200 border-transparent",
};

interface ButtonProps {
	className?: string;
	ringColor?: string;
	theme?: "gray" | "orange" | "orangeLight" | null;
	loading?: boolean;
	spinnerClasses?: string;
}

export default defineComponent({
	name: "Button",
	props: {
		className: {
			type: String,
			default: "",
		},
		ringColor: {
			type: String,
			default: "",
		},
		theme: {
			type: String as PropType<ButtonProps["theme"]>,
			default: null,
		},
		loading: {
			type: Boolean as PropType<ButtonProps["loading"]>,
			default: false,
		},
		spinnerClasses: {
			type: String,
			default: "h-4 text-gray-100 fill-orange-400",
		},
		disabled: {
			type: Boolean,
			default: false,
		},
	},
	setup(props: ButtonProps) {
		return {
			themes,
			classNames,
		};
	},
});
</script>

<template>
	<button :class="[
		'inline-flex justify-center relative ease-in-out items-center no-bad-scale px-4 py-2 text-base font-medium rounded-md border shadow-sm duration-200 font-inter focus:outline-none sm:text-sm',
		theme && themes[theme],
		className,
		loading && '!text-transparent',
		ringColor !== '' ? `focus:ring-2 focus:ring-offset-2 focus:ring-${ringColor}` : 'ring-0 focus:ring-0'
	]" :disabled="disabled || loading">
		<svg v-if="loading" role="status" :class="['animate-spin absolute w-auto', spinnerClasses]" viewBox="0 0 100 101"
			fill="none" xmlns="http://www.w3.org/2000/svg">
			<path
				d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
				fill="currentColor" />
			<path
				d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
				fill="currentFill" />
		</svg>
		<slot />
	</button>
</template>
