// src/components/transitions/Link.tsx
import { JSXInternal } from "preact/src/jsx";
import { useStore } from "utils/store";

export function Link(props: JSXInternal.HTMLAttributes<HTMLAnchorElement>) {
	const [state, setState] = useStore();

	return (
		<a
			{...props}
			onClick={e => {
				if (!e.ctrlKey && !e.metaKey) {
					e.preventDefault();
					setState(s => ({
						...s,
						path: props.href as string,
					}));
				}
			}}></a>
	);
}

// components/transitions/Link.vue
<template>
	<a v-bind="$attrs" :href="props.href" @click="handleClick">
		<slot />
	</a>
</template>

<script setup lang="ts">
import { useStore } from "../../utils/store";

const store = useStore();

const props = defineProps<{
	sidebar?: string;
	href: string;
}>();

const handleClick = (e: MouseEvent) => {
	if (!e.ctrlKey && !e.metaKey) {
		if (props.sidebar) {
			e.preventDefault();

			store.state.postViewer = true;
		} else {
			store.state.notifications = false;
			store.state.postViewer = false;
		}
	}
};
</script>
