// components/nav/MobileNavbar.tsx
import { Dialog, Transition } from "@headlessui/react";
import {
	IconBell,
	IconMenu2,
	IconPaperclip,
	IconPencilPlus,
	IconPlus,
	IconX,
} from "@tabler/icons-react";
import Button from "components/buttons/Button";
import { AuthContext } from "components/context/AuthContext";
import { StateContext } from "components/context/StateContext";
import SmallSelect from "components/forms/SmallSelect";
import { Response } from "megalodon";
import SmallLogo from "components/logo/SmallLogo";
import NotificationsFeed from "components/feed/NotificationsFeed";
import Link from "next/link";
import { useState, Fragment, useContext, FormEvent, MutableRefObject, useRef } from "react";
import toast from "react-hot-toast";
import { MobileNav } from "components/sidebar/Nav";

export default function MobileNavbar() {
	const [state, setState]: any = useContext(StateContext);
	const client = useContext(AuthContext);

	return (
		<>
			<header className="flex fixed inset-x-0 top-0 z-30 justify-between items-center px-6 py-3 bg-white border-b dark:border-gray-700 bg-dark md:hidden">
				<Button
					style="gray"
					className="!p-3 !border-none !shadow-none"
					onClick={() => {
						setState(s => ({
							...s,
							sidebarOpened: true,
						}));
					}}>
					<IconMenu2 aria-hidden={true} className="" />
					<span className="sr-only">Open sidebar</span>
				</Button>
				<Link href="/">
					<SmallLogo size="w-10 !h-10" />
				</Link>
				<Button
					style="gray"
					className="!p-3 !border-none !shadow-none"
					onClick={() => {
						setState(s => ({
							...s,
							notificationsOpened: true,
						}));
					}}>
					<IconBell aria-hidden={true} className="" />
					<span className="sr-only">Open notifications</span>
				</Button>
			</header>
			<div className="fixed right-0 bottom-0 z-30 mx-7 my-7">
				<Button
					onClick={() => {
						setState(s => ({
							...s,
							mobileEditorOpened: true,
						}));
					}}
					style="gray"
					className="bg-gray-200 !p-3">
					<IconPencilPlus className="w-10 h-10" aria-hidden={true} />
					<span className="sr-only">Compose new post</span>
				</Button>
			</div>
			<Transition.Root unmount={false} show={state.notificationsOpened} as={Fragment}>
				<Dialog
					as="div"
					className="relative z-40"
					onClose={() => {
						setState(s => ({
							...s,
							notificationsOpened: false,
						}));
					}}
					unmount={false}>
					<Transition.Child
						as={Fragment}
						enter="ease-in-out duration-500"
						enterFrom="opacity-0"
						enterTo="opacity-100"
						leave="ease-in-out duration-500"
						leaveFrom="opacity-100"
						leaveTo="opacity-0"
						unmount={false}>
						<div className="fixed inset-0 backdrop-filter backdrop-blur-sm transition-opacity bg-gray-400/40" />
					</Transition.Child>

					<div className="overflow-hidden fixed inset-0">
						<div className="overflow-hidden absolute inset-0">
							<div className="flex fixed inset-y-0 right-0 ml-10 max-w-full pointer-events-none">
								<Transition.Child
									unmount={false}
									as={Fragment}
									enter="transform transition ease-in-out duration-300 sm:duration-700"
									enterFrom="translate-x-full"
									enterTo="translate-x-0"
									leave="transform transition ease-in-out duration-300 sm:duration-700"
									leaveFrom="translate-x-0"
									leaveTo="translate-x-full">
									<Dialog.Panel
										className="overflow-hidden relative w-screen max-w-md pointer-events-auto">
										<Transition.Child
											unmount={false}
											as={Fragment}
											enter="ease-in-out duration-300"
											enterFrom="opacity-0"
											enterTo="opacity-100"
											leave="ease-in-out duration-300"
											leaveFrom="opacity-100"
											leaveTo="opacity-0">
											<div className="flex absolute top-0 left-0 pt-4 pr-2 -ml-8 sm:-ml-10 sm:pr-4"></div>
										</Transition.Child>
										<div className="flex overflow-y-hidden flex-col pt-6 h-full bg-white shadow-xl bg-dark">
											<div className="flex justify-between px-4 sm:px-6">
												<Dialog.Title className="text-lg font-medium text-gray-900 dark:text-gray-50">
													Notifications
												</Dialog.Title>
												<button
													type="button"
													className="text-gray-300 rounded-md hover:text-white focus:outline-none"
													onClick={() =>
														setState(s => ({
															...s,
															notificationsOpened: false,
														}))
													}>
													<span className="sr-only">Close panel</span>
													<IconX className="w-6 h-6" aria-hidden="true" />
												</button>
											</div>
											<div className="flex overflow-hidden relative px-4 mt-6 max-w-full grow sm:px-6">
												<NotificationsFeed withTitle={false} />
											</div>
										</div>
									</Dialog.Panel>
								</Transition.Child>
							</div>
						</div>
					</div>
				</Dialog>
			</Transition.Root>
			<Transition.Root show={state.sidebarOpened} as={Fragment}>
				<Dialog
					as="div"
					className="relative z-40"
					onClose={() => {
						setState(s => ({
							...s,
							notificationsOpened: false,
						}));
					}}
					unmount={false}>
					<Transition.Child
						as={Fragment}
						enter="ease-in-out duration-500"
						enterFrom="opacity-0"
						enterTo="opacity-100"
						leave="ease-in-out duration-500"
						leaveFrom="opacity-100"
						leaveTo="opacity-0">
						<div className="fixed inset-0 backdrop-filter backdrop-blur-sm transition-opacity bg-gray-400/40" />
					</Transition.Child>

					<div className="overflow-hidden fixed inset-0">
						<div className="overflow-hidden absolute inset-0">
							<div className="flex fixed inset-y-0 left-0 mr-10 max-w-full pointer-events-none">
								<Transition.Child
									as={Fragment}
									enter="transform transition ease-in-out duration-300 sm:duration-700"
									enterFrom="-translate-x-full"
									enterTo="translate-x-0"
									leave="transform transition ease-in-out duration-300 sm:duration-700"
									leaveFrom="-translate-x-0"
									leaveTo="translate-x-full">
									<Dialog.Panel className="overflow-hidden relative w-screen max-w-md pointer-events-auto">
										<Transition.Child
											as={Fragment}
											enter="ease-in-out duration-300"
											enterFrom="opacity-0"
											enterTo="opacity-100"
											leave="ease-in-out duration-300"
											leaveFrom="opacity-100"
											leaveTo="opacity-0">
											<div className="flex absolute top-0 right-0 pt-4 pl-2 -mr-8 sm:-mr-10 sm:pl-4"></div>
										</Transition.Child>
										<div className="flex overflow-y-hidden flex-col py-6 max-w-xs h-full bg-white shadow-xl bg-dark">
											<div className="flex justify-between px-4 sm:px-6">
												<Dialog.Title className="text-lg font-medium text-gray-900 dark:text-gray-50">
													Fedibase
												</Dialog.Title>
												<button
													type="button"
													className="text-gray-300 rounded-md hover:text-white focus:outline-none"
													onClick={() =>
														setState(s => ({
															...s,
															sidebarOpened: false,
														}))
													}>
													<span className="sr-only">Close panel</span>
													<IconX className="w-6 h-6" aria-hidden="true" />
												</button>
											</div>
											<div className="flex overflow-hidden relative px-4 mt-6 max-w-full h-full sm:px-6">
												<MobileNav />
											</div>
										</div>
									</Dialog.Panel>
								</Transition.Child>
							</div>
						</div>
					</div>
				</Dialog>
			</Transition.Root>
		</>
	);
}

// src/components/layout/MobileNavbar.vue
<script setup lang="ts">
import { store } from "../../utils/store";
import { IconSun, IconMoon, IconHome, IconBell, IconPencilPlus } from "@tabler/icons-vue";
import Button from "../button/Button.vue";
import Link from "../transitions/Link.vue";
import { Dialog, DialogPanel, DialogTitle, TransitionChild, TransitionRoot } from "@headlessui/vue";
import { IconX } from "@tabler/icons-vue";
import NotificationsFeed from "../feed/NotificationsFeed.vue";

const toggleTheme = () => {
	if (store.theme === "dark") {
		store.theme = "light"

		document.getElementsByTagName("html")[0].classList.remove("dark");
	} else if (store.theme === "light") {
		store.theme = "dark"

		document.getElementsByTagName("html")[0].classList.add("dark");
	}
}

const _window = window;

const composeNewPost = () => {
	store.state.composer = true;
}

const openNotifications = () => {
	store.state.notifications = true;
}

const closeNotifications = () => {
	store.state.notifications = false;
}

</script>

<template>
	<header
		class="flex fixed inset-x-0 bottom-0 z-[999999] justify-between items-center px-6 py-2 bg-white border-b dark:border-gray-700 dark:bg-dark-800 md:hidden">
		<Button theme="gray" class="!p-3 !border-none !shadow-none !bg-white dark:!bg-transparent" @click="toggleTheme">
			<IconSun v-if="store.theme === 'light'" aria-hidden="true" />
			<IconMoon v-if="store.theme === 'dark'" aria-hidden="true" />
		</Button>
		<Link href="/">
			<Button theme="gray" class="!p-3 !border-none !shadow-none !bg-white dark:!bg-transparent" title="Visit main feed">
				<IconHome aria-hidden="true" />
			</Button>
		</Link>
		<Button theme="gray" title="Compose new post" @click="composeNewPost"
			class="!p-3 !border-none !shadow-none !bg-white dark:!bg-transparent">
			<IconPencilPlus aria-hidden="true" />
		</Button>
		<Button theme="gray" title="Open notifications"
			@click="openNotifications"
			class="!p-3 !border-none !shadow-none !bg-white dark:!bg-transparent">
			<IconBell aria-hidden="true" />
		</Button>
		<Button theme="gray" title="Your avatar" class="!p-0 !border-none !shadow-none !bg-white dark:!bg-transparent">
			<img :src="store.auth.data?.avatar" class="w-9 h-9 rounded border-2" alt="Your avatar" />
		</Button>
	</header>

	<TransitionRoot as="template" :show="store.state.notifications &&
		_window.innerWidth < 768">
		<Dialog as="div" :unmount="false" class="flex fixed inset-y-0 top-0 bottom-16 max-w-full pointer-events-none">
				<TransitionChild :unmount="false" as="template" enter="ease-out duration-100"
					enterFrom="opacity-0 translate-y-4 translate-y-0 scale-95" enterTo="opacity-100 translate-y-0 scale-100"
					leave="ease-in duration-100" leaveFrom="opacity-100 translate-y-0 scale-100"
					leaveTo="opacity-0 translate-y-4 translate-y-0 scale-95">
					<DialogPanel class="overflow-hidden relative w-screen max-w-md pointer-events-auto">
						<div class="flex overflow-y-hidden flex-col pt-6 h-full bg-white shadow-xl dark:bg-dark-800">
							<div class="flex justify-between px-4 sm:px-6">
								<DialogTitle class="text-lg font-medium text-gray-900 dark:text-gray-50">
									Notifications
								</DialogTitle>
								<button type="button"
									@click="closeNotifications"
									class="text-gray-300 rounded-md dark:hover:text-white focus:outline-none">
									<span class="sr-only">
										Close panel
									</span>
									<IconX class="w-6 h-6" aria-hidden="true" />
								</button>
							</div>
							<div class="flex overflow-hidden relative px-4 mt-6 max-w-full grow sm:px-6">
								<NotificationsFeed :title="false" />
							</div>
						</div>
					</DialogPanel>
				</TransitionChild>
		</Dialog>
	</TransitionRoot>
</template>
