// src/components/transitions/Link.tsx
import { JSXInternal } from "preact/src/jsx";
import { useStore } from "utils/store";

export function Link(props: JSXInternal.HTMLAttributes<HTMLAnchorElement> & {
	sidebar?: string
}) {
	const [, setPath] = useStore.path();
	const [, setConversation] = useStore.viewingConversation();
	const [, setMobilePostViewer] = useStore.mobilePostViewer();

	return (
		<a
			{...props}
			onClick={e => {
				if (!e.ctrlKey && !e.metaKey) {
					e.preventDefault();
					
					if (props.sidebar) {
						setConversation(props.sidebar);
						setMobilePostViewer(true);
					} else {
						history.pushState(null, "", props.href as string);
						setPath(props.href as string);
					}
				}
			}}>
		</a>
	);
}

// src/components/transitions/Link.vue
<template>
	<a v-bind="$attrs" @click="handleClick" :href="props.href">
		<slot />
	</a>
</template>

<script setup lang="ts">
import { store } from '../../utils/store';

const props = defineProps<{
	sidebar?: string;
	href: string;
}>()

const handleClick = (e: MouseEvent) => {
	if (!e.ctrlKey && !e.metaKey) {
		e.preventDefault();

		if (props.sidebar) {
			store.state.postViewer = true;
			store.viewingConversation = props.sidebar
		} else {
			history.pushState(null, "", props.href);
			store.path = props.href;
		}
	}
};
</script>
