// components/posts/Status.tsx
/* eslint-disable @next/next/no-img-element */
import { IconMessage } from "@tabler/icons-react";
import Button from "components/buttons/Button";
import { AuthContext } from "components/context/AuthContext";
import { Entity } from "megalodon";
import Link from "next/link";
import { Dispatch, SetStateAction, useContext, useEffect, useRef, useState } from "react";
import { fromNow, withEmojis } from "utils/functions";
import InteractionBar from "./InteractionBar";
import PostImages from "./PostImages";

export default function Status({
	status,
	type,
	showInteraction = true
}: {
	status: Entity.Status;
	type: "notification" | "post"; // Notification renders slightly different than a normal post
	showInteraction?: boolean;
}) {
	const [expand, setExpand] = useState<boolean>(false);
	const [showText, setShowText] = useState<boolean>(false);	
	const textRef = useRef<HTMLParagraphElement>(null);
	const [inReplyAccount, setInReplyAccount] = useState<Entity.Account>();
	const client = useContext(AuthContext);

	useEffect(() => {
		// If the post is a reply, get the previous post's contents
		if (status.in_reply_to_account_id && !inReplyAccount) client?.getAccount(status.in_reply_to_account_id).then(data => {
			setInReplyAccount(data.data);
		});
	}, [client, inReplyAccount, status.in_reply_to_account_id])

	return (
		<div className="flex flex-col max-w-full">
			<div className="flex flex-row max-w-full">
				<Link href={`/users/@${status.account.id}`} className="flex-shrink-0 mr-4">
					<img
						alt={status.account.acct}
						src={status.account.avatar}
						className={`${
							type == "post" ? "w-14 h-14" : "w-8 h-8"
						} text-gray-300 bg-white rounded border border-gray-300`}
					/>
				</Link>
				<div className="flex flex-col min-w-0 grow">
					<div className="flex flex-col justify-between gap-x-2 text-[0.95rem] md:flex-row">
						<span className="inline overflow-hidden whitespace-nowrap text-ellipsis">
							<h4 className="inline font-bold" title={status.account.display_name}>
								{withEmojis(status.account.display_name, status.account.emojis)}
							</h4>
							<h6
								title={status.account.acct}
								className="inline overflow-hidden ml-0 text-gray-500 overflow-ellipsis md:ml-2">
								@{status.account.acct}
							</h6>
						</span>
						<div className="whitespace-nowrap">
							<Link href={`/posts/${status.id}`} className="text-sm text-gray-700 hover:underline">
								{fromNow(new Date(status.created_at))}
							</Link>
						</div>
					</div>
					<div className="flex flex-col gap-y-1">
						{status.in_reply_to_id && (
							<span className="text-xs text-gray-600 hover:underline">
								<IconMessage className="inline mr-1 w-4 h-4" />
								Replying to{" "}
								{inReplyAccount &&
									withEmojis(
										inReplyAccount?.display_name,
										inReplyAccount?.emojis,
									)}
							</span>
						)}
						<SensitiveTextSpoiler
							status={status}
							showText={showText}
							setShowText={setShowText}
						/>

						<div
							className="relative w-full text-sm"
							style={{
								overflow: expand ? "" : "hidden",
								maxHeight: expand ? "" : "8rem",
							}}>
							<p
								ref={textRef}
								className={`mt-1 rounded duration-200 status-text ${
									status.sensitive && !showText && "filter blur-lg"
								}`}>
								{withEmojis(status.content, status.emojis)}
							</p>
						</div>

						{textRef?.current?.offsetHeight > 128 && (
							<>
								<hr />
								<button
									className="mx-auto w-full text-sm text-blue-800 hover:underline"
									onClick={() => {
										setExpand(!expand);
									}}>
									{expand === true ? "Less" : "More"}
								</button>
							</>
						)}
					</div>
					<PostImages status={status} />
				</div>
			</div>

			{showInteraction && <InteractionBar status={status} />}
		</div>
	);
}

function SensitiveTextSpoiler({
	status,
	showText,
	setShowText,
}: {
	status: Entity.Status;
	showText: boolean;
	setShowText: Dispatch<SetStateAction<boolean>>;
}) {
	return (
		<>
			{status.sensitive && (
				<div className="flex gap-x-2 items-center font-bold">
					{status.spoiler_text == "" ? "Marked as sensitive" : status.spoiler_text}

					<Button
						style="gray"
						className="!py-1 !px-2"
						onClick={() => {
							setShowText(t => !t);
						}}>
						{showText ? "Hide" : "Show"}
					</Button>
				</div>
			)}
		</>
	);
}

// src/components/status/Status.vue
<script setup lang="ts">
import { Entity } from 'megalodon';
import { onMounted, ref } from 'vue';
import { classNames, withEmojis, fromNow } from '../../utils/functions';
import InteractionBar from './InteractionBar.vue';
import Button from '../button/Button.vue';
import ScaleFadeSlide from '../transitions/ScaleFadeSlide.vue';
import StatusAttachments from './StatusAttachments.vue';
import Link from '../transitions/Link.vue';
import ReplyTo from './ReplyTo.vue';
import Poll from './Poll.vue';
import Reactions from './Reactions.vue';

const props = defineProps<{
	status: Entity.Status;
	interaction: boolean;
	type: PostType;
}>();

const expand = ref<boolean>(false);
const clamps = ref<boolean>(true);
const show = ref<boolean>(false);
const textRef = ref<HTMLParagraphElement>();

onMounted(() => {
	if (textRef.value) {
		const lineHeight = parseInt(getComputedStyle(textRef.value).lineHeight) / 2;
		const height = textRef.value.clientHeight
		const maxLines = 6;
		const maxAllowedHeight = lineHeight * maxLines;
		const isOverflowing = height > maxAllowedHeight;
		clamps.value = isOverflowing;
	}
});

const toggleExpand = () => {
	expand.value = !expand.value
}

const toggleShow = () => {
	show.value = !show.value
}
</script>

<script lang="ts">
export enum PostType {
	Normal,
	Small
}
</script>

<template>
	<ScaleFadeSlide>
		<div class="flex flex-col max-w-full font-inter cursor-pointer">
			<div class="flex flex-col min-w-0 grow gap-y-1">
				<div class="flex flex-row overflow-hidden text-[0.95rem] text-ellipsis whitespace-nowrap w-full">
					<Link :href="`/users/${status.account.id}`" class="flex-shrink-0 mr-2" :title="`${status.account.display_name}'s profile'`">
						<img loading="lazy" alt="" :src="status.account.avatar"
							:class="['bg-white overflow-hidden dark:dark:bg-dark-800-800 rounded border border-gray-300 dark:border-gray-700',
							type === PostType.Normal ? 'w-12 h-12' : 'w-10 h-10']" />
					</Link>
					<div :class="['flex flex-col grow', type === PostType.Small && 'text-sm']">
						<h4 class="font-bold dark:text-gray-200" :title="status.account.display_name"
							v-html="withEmojis(status.account.display_name, status.account.emojis)">
						</h4>
						<h5 :title="status.account.acct"
							class="overflow-hidden ml-0 text-gray-500 overflow-ellipsis dark:text-gray-400">
							@{{ status.account.acct }}
						</h5>
					</div>
					<Link :href="`/posts/${status.id}`" :sidebar="status.id" class="text-sm text-gray-700 dark:text-gray-300 hover:underline"
						v-html="fromNow(new Date(status.created_at))">
					</Link>
				</div>
				<div class="flex flex-col gap-y-1">
					<ReplyTo v-if="status.in_reply_to_id" :status="status" />

					<div v-if="status.sensitive" class="flex gap-x-2 items-center font-bold dark:text-gray-100">
						{{ status.spoiler_text === "" ? "Marked as sensitive" : withEmojis(status.spoiler_text,
							status.emojis) }}

						<Button class="!py-1 !px-2" @click="toggleShow" theme="gray">
							{{ show ? 'Hide' : 'Show' }}
						</Button>
					</div>

					<p ref="textRef" v-html="withEmojis(status.content, status.emojis)"
						:class="classNames('mt-1 status-text rounded text-sm duration-200 status-text dark:text-gray-50 break-words w-full', status.sensitive && !show && 'filter blur-lg', clamps && !expand && 'line-clamp-6')">

					</p>


					<button v-if="clamps" @click="toggleExpand"
						class="mx-auto w-full text-sm text-blue-800 dark:text-blue-100 hover:underline">
						<template v-if="expand">Less</template>
						<template v-else="expand">More</template>
					</button>

					<Poll v-if="status.poll" :status="status" />

					<Reactions :status="status" v-if="status.emoji_reactions.length > 0" />

					<StatusAttachments :status="status" v-if="status.media_attachments.length > 0"/>
				</div>
			</div>

			<InteractionBar v-if="props.interaction" :status="status" />
		</div>
	</ScaleFadeSlide></template>
