// components/layout/MobileNavbar.vue
<script setup lang="ts">
import { store } from "../../utils/store";
import {
	IconSun,
	IconMoon,
	IconHome,
	IconBell,
	IconPencilPlus,
} from "@tabler/icons-vue";
import Button from "../button/Button.vue";
import {
	Dialog,
	DialogPanel,
	DialogTitle,
	TransitionChild,
	TransitionRoot,
} from "@headlessui/vue";
import { IconX } from "@tabler/icons-vue";
import NotificationsFeed from "../feed/NotificationsFeed.vue";
import Conversation from "../feed/Conversation.vue";
import { IconChevronDown } from "@tabler/icons-vue";

const toggleTheme = () => {
	if (store.theme === "dark") {
		store.theme = "light";

		document.getElementsByTagName("html")[0].classList.remove("dark");
	} else if (store.theme === "light") {
		store.theme = "dark";

		document.getElementsByTagName("html")[0].classList.add("dark");
	}
};

const _window = window;

const composeNewPost = () => {
	store.state.composer = true;
};

const openNotifications = () => {
	store.state.notifications = true;
};

const closeNotifications = () => {
	store.state.notifications = false;
};

const closePostViewer = () => {
	store.state.postViewer = false;
};
</script>

<style scoped lang="postcss">
.element {
	@apply !px-0 !py-0 !p-3 h-full !rounded-none grow dark:hover:!bg-dark-600 hover:!bg-gray-300 !bg-transparent !border-none !shadow-none !bg-white dark:!bg-transparent;
}

.element a,
.element {
	@apply flex items-center justify-center text-xs flex-col gap-y-1;
}
</style>

<template>
	<header
		:class="[
			'fixed inset-x-0 -bottom-1 z-[999999] border-t p-0 overflow-hidden rounded-t items-center justify-around grid grid-cols-4 h-16 bg-white border-b dark:border-gray-700 dark:bg-dark-800 md:hidden',
		]">
		<Button theme="gray" class="element" @click="toggleTheme">
			<IconSun v-if="store.theme === 'light'" aria-hidden="true" />
			<IconMoon v-if="store.theme === 'dark'" aria-hidden="true" />
			<span>Theme</span>
		</Button>
		<Button theme="gray" class="element" title="Visit main feed">
			<RouterLink to="/">
				<IconHome aria-hidden="true" />
				<span>Home</span>
			</RouterLink>
		</Button>
		<Button
			theme="gray"
			title="Compose new post"
			@click="composeNewPost"
			class="element">
			<IconPencilPlus aria-hidden="true" />
			<span>Compose</span>
		</Button>
		<Button theme="gray" title="Open notifications" class="element">
			<RouterLink to="/notifications">
				<IconBell aria-hidden="true" />
				<span>Notifications</span>
			</RouterLink>
		</Button>
	</header>
</template>

// src/components/nav/MobileNavbar.tsx
import { Dialog, Transition } from "@headlessui/react";
import { IconBell, IconHome, IconMoon, IconPencilPlus, IconSun, IconX } from "@tabler/icons-preact";
import { Button } from "components/buttons/Button";
import NotificationsFeed from "components/feed/NotificationsFeed";
import { Fragment } from "preact/jsx-runtime";
import { Entity } from "megalodon";
import { AuthContext } from "components/context/AuthContext";
import { useContext, useEffect, useState } from "preact/hooks";
import toast from "react-hot-toast";
import { useStore } from "utils/store";
import { Link } from "components/transitions/Link";

export default function MobileNavbar() {
	const [state, setState] = useStore();
	const [account, setAccount] = useState<Entity.Account | null>(null);
	const client = useContext(AuthContext);
	const [theme, setTheme] = useState<string>("light");

	useEffect(() => {
		client
			?.verifyAccountCredentials()
			.then(data => {
				setAccount(data.data);
			})
			.catch(err => {
				console.error(err);
				toast.error("Couldn't load account data :(");
			});
		
		setTheme((localStorage.getItem("theme") ?? "light").toString());
	}, []);


	const toggleTheme = () => {
		const html = document.getElementsByTagName("html")[0];
		const themeCookie = (localStorage.getItem("theme") ?? "light").toString();
		if (themeCookie === "dark") {
			localStorage.setItem("theme", "light");
			html.className = html.className.replaceAll("dark", "");
			setTheme("light");
		} else if (themeCookie === "light") {
			localStorage.setItem("theme", "dark");
			html.className = html.className + " dark";
			setTheme("dark");
		}
	};

	return (
		<>
			<header className="flex fixed inset-x-0 bottom-0 z-30 justify-between items-center px-6 py-2 bg-white border-b dark:border-gray-700 dark:bg-dark-800 md:hidden">
				<Button
					theme="gray"
					className="!p-3 !border-none !shadow-none !bg-white dark:!bg-transparent"
					title={theme === "light" ? "Enable dark mode" : "Enable light mode"}
					onClick={toggleTheme}>
					{theme === "light" && (
						<>
							<IconSun aria-hidden={true} />
						</>
					)}
					{theme === "dark" && (
						<>
							<IconMoon aria-hidden={true} />
						</>
					)}
				</Button>
				<Link href="/">
					<Button
						theme="gray"
						className="!p-3 !border-none !shadow-none !bg-white dark:!bg-transparent"
						title="Visit main feed">
						<IconHome aria-hidden={true} className="" />
						<span className="sr-only">Visit main feed</span>
					</Button>
				</Link>
				<Button
					theme="gray"
					className="!p-3 !border-none !shadow-none !bg-white dark:!bg-transparent"
					onClick={() => {
						setState(prev => ({
							...prev,
							postComposerOpened: true,
						}));
					}}>
					<IconPencilPlus aria-hidden={true} />
					<span className="sr-only">Compose new post</span>
				</Button>
				<Button
					theme="gray"
					className="!p-3 !border-none !shadow-none !bg-white dark:!bg-transparent"
					onClick={() => {
						setState(prev => ({
							...prev,
							notificationsOpened: true,
						}));
					}}>
					<IconBell aria-hidden={true} />
					<span className="sr-only">Open notifications</span>
				</Button>
				<Button theme="gray" className="!p-0 !border-none !shadow-none !bg-white dark:!bg-transparent" onClick={() => {
					setState(prev => ({
						...prev,
						settingsOpen: true,
					}));
				}}>
					<img
						src={account?.avatar}
						className="w-9 h-9 rounded border-2"
						alt="Your avatar"
					/>
					<span className="sr-only">Your avatar</span>
				</Button>
			</header>
			<Transition.Root
				unmount={window.innerWidth > 768}
				show={
					state.notificationsOpened &&
					window.innerWidth < 768 &&
					!state.postComposerOpened
				}
				as={Fragment}>
				<Dialog
					as="div"
					className="relative"
					onClose={() => {
						setState(prev => ({
							...prev,
							postComposerOpened: false,
						}));
					}}
					unmount={false}>
					<div className="flex fixed inset-y-0 right-0 ml-10 max-w-full pointer-events-none">
						<Transition.Child
							unmount={false}
							as={Fragment}
							enter="ease-out duration-100"
							enterFrom="opacity-0 translate-y-4 translate-y-0 scale-95"
							enterTo="opacity-100 translate-y-0 scale-100"
							leave="ease-in duration-100"
							leaveFrom="opacity-100 translate-y-0 scale-100"
							leaveTo="opacity-0 translate-y-4 translate-y-0 scale-95">
							<Dialog.Panel className="overflow-hidden relative w-screen max-w-md pointer-events-auto">
								<div className="flex overflow-y-hidden flex-col pt-6 h-full bg-white shadow-xl dark:bg-dark-800">
									<div className="flex justify-between px-4 sm:px-6">
										<Dialog.Title className="text-lg font-medium text-gray-900 dark:text-gray-50">
											Notifications
										</Dialog.Title>
										<button
											type="button"
											className="text-gray-300 rounded-md hover:text-white dark:hover:text-black focus:outline-none"
											onClick={() => {
												setState(prev => ({
													...prev,
													notificationsOpened: false,
												}));
											}}>
											<span className="sr-only">Close panel</span>
											<IconX className="w-6 h-6" aria-hidden="true" />
										</button>
									</div>
									<div className="flex overflow-hidden relative px-4 mt-6 max-w-full grow sm:px-6">
										<NotificationsFeed withTitle={false} />
									</div>
								</div>
							</Dialog.Panel>
						</Transition.Child>
					</div>
				</Dialog>
			</Transition.Root>
		</>
	);
}
