// components/select/Select.vue
<script lang="ts">
import {
	Listbox,
	ListboxButton,
	ListboxOption,
	ListboxOptions,
} from "@headlessui/vue";

export enum SelectDirection {
	Right = "right",
	Left = "left",
	Center = "center",
}

export enum SelectOrientation {
	Up = "up",
	Down = "down",
}

export interface SelectItem {
	text: string;
	value: string;
	icon: any;
	description?: string;
}
</script>

<script setup lang="ts">
interface SelectProps {
	items: SelectItem[];
	defaultValue: number;
	direction?: SelectDirection;
	orientation?: SelectOrientation;
	name?: string;
}

const props = defineProps<SelectProps>();
const emit = defineEmits(["update:model-value"]);

const selected = ref<SelectItem["value"]>(
	props.items[props.defaultValue].value
);
</script>

<template>
	<Listbox
		v-model="selected"
		:name="name"
		as="div"
		class="relative"
		@update:model-value="value => emit('update:model-value', value)">
		<ListboxButton
			class="flex text-sm relative flex-row w-full gap-x-3 items-center p-2 text-gray-600 rounded duration-200 cursor-default dark:text-gray-300 hover:bg-gray-100 border border-dark-600 dark:hover:bg-dark-700">
			<Icon
				:name="items.find(i => i.value == selected)?.icon"
				:stroke-width="2"
				class="w-5 h-5"
				aria-hidden="true" />
			<span class="">{{
				items.find(i => i.value == selected)?.text
			}}</span>
			<Icon name="ic:round-expand-more" class="ml-auto w-5 h-5" />
		</ListboxButton>
		<Transition
			appear
			enter-from-class="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
			enter-to-class="opacity-100 translate-y-0 sm:scale-100"
			enter-active-class="ease-out duration-100"
			leave-active-class="ease-in duration-100"
			leave-from-class="opacity-100 translate-y-0 sm:scale-100"
			leave-to-class="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95">
			<ListboxOptions
				:class="[
					'absolute z-30 w-full shadow-lg mt-1 text-base rounded-md overflow-hidden bg-gray-100/75 border border-dark-700 dark:bg-dark-800/75 backdrop-blur-md',
					direction === SelectDirection.Left &&
						'right-0 origin-top-right',
					direction === SelectDirection.Center &&
						'right-0 origin-top-right translate-x-[50%]',
					orientation === SelectOrientation.Up && 'bottom-[110%]',
				]">
				<ListboxOption
					v-for="item in items"
					:key="item.value"
					:value="item.value"
					:class="[
						'flex relative flex-row gap-x-3 items-center py-2 px-3 text-gray-800 dark:text-gray-100 duration-200 cursor-default select-none hover:bg-gray-200 dark:hover:bg-dark-700/75',
					]">
					<Icon
						:name="item.icon"
						class="w-5 h-auto text-gray-500"
						aria-hidden="true" />
					<div class="flex flex-col">
						<span class="text-sm font-semibold font-poppins">
							{{ item.text }}
						</span>
						<span
							v-if="item.description"
							class="text-sm min-w-40 text-orange-700 dark:text-orange-200">
							{{ item.description ?? "" }}
						</span>
					</div>
					<Icon
						v-if="selected === item.value"
						class="ml-auto"
						name="ic:round-check" />
				</ListboxOption>
			</ListboxOptions>
		</Transition>
	</Listbox>
</template>

// src/components/forms/Select.tsx
import { Listbox, Transition } from "@headlessui/react";
import { IconChevronsUp } from "@tabler/icons-preact";
import { Fragment } from "preact/jsx-runtime";

interface SelectOptions {
	items: SelectItem[];
	selected: any;
	setSelected: any;
}

interface SelectItem {
	text: string;
	value: string;
	icon: any;
}

export default function Select({ items, selected, setSelected }: SelectOptions) {
	return (
		<div className="w-full">
			<Listbox
				value={selected}
				onChange={value => {
					items.map(item => {
						if (item.value == value) {
							setSelected(item);
						}
					});
				}}>
				<div className="relative mt-1">
					<Listbox.Button className="relative py-2 pr-10 pl-3 w-full text-left bg-white rounded border shadow-sm cursor-default bg-dark dark:border-gray-700 dark:text-gray-100 focus:outline-none focus-visible:border-indigo-500 focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-orange-300 sm:text-sm">
						<span className="block truncate">{selected.text}</span>
						<span className="flex absolute inset-y-0 right-0 items-center pr-2 pointer-events-none">
							<IconChevronsUp className="w-5 h-5 text-gray-400" aria-hidden="true" />
						</span>
					</Listbox.Button>
					<Transition
						as={Fragment}
						enter="ease-out duration-200"
						enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
						enterTo="opacity-100 translate-y-0 sm:scale-100"
						leave="ease-in duration-200"
						leaveFrom="opacity-100 translate-y-0 sm:scale-100"
						leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95">
						<Listbox.Options className="overflow-auto absolute z-20 mt-1 w-full max-h-60 text-base bg-white rounded-md shadow-lg outline-none bg-dark font-inter focus:outline-none sm:text-sm">
							{items.map(item => (
								<Listbox.Option
									key={item.text}
									className={`flex relative flex-row gap-x-3 items-center px-4 py-2 duration-200 hover:bg-gray-200 hover:dark:bg-gray-700 dark:text-gray-100`}
									value={item.value}>
									{({ selected }) => (
										<>
											<item.icon className="w-4 h-4"/>
											<span
												className={`block truncate`}>
												{item.text}
											</span>
										</>
									)}
								</Listbox.Option>
							))}
						</Listbox.Options>
					</Transition>
				</div>
			</Listbox>
		</div>
	);
}
