// components/input/Input.vue
<script setup lang="ts">
interface InputProps {
	loading?: boolean;
	name: string;
	class?: string;
	icon?: any;
}

const props = defineProps<InputProps>();
</script>

<script lang="ts">
export default {
	inheritAttrs: false,
};
</script>

<template>
	<div class="relative">
		<input
			:name="props.name"
			:disabled="props.loading"
			:class="[
				'block pr-3 py-2 focus:shadow-xl w-full pt-[0.6rem] pl-8 placeholder-gray-500 bg-white rounded-md border border-gray-300 shadow-sm duration-200 appearance-none outline-none dark:text-gray-100 dark:bg-dark-800 dark:border-dark-700 disabled:bg-gray-100 focus:outline-none sm:text-sm',
				props.class,
			]"
			v-bind="$attrs" />
		<div v-if="icon" class="absolute left-2 inset-y-0 flex items-center">
			<component :is="icon" class="w-5 h-5 text-gray-400" />
		</div>
	</div>
</template>

// components/forms/Input.tsx
import { DetailedHTMLProps, InputHTMLAttributes } from "react";
import { classNames } from "utils/functions";

interface InputOptions {
	isLoading: boolean;
	children: any;
	name: string;
}

export function Input({
	isLoading,
	children,
	name,
	className = "",
	...props
}: InputOptions & DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>) {
	return (
		<div>
			{children}
			<div className="mt-1">
				<input
					name={name}
					disabled={isLoading}
					className={classNames(
						"block px-3 py-2 w-full placeholder-gray-400 bg-white rounded-md border border-gray-300 shadow-sm duration-200 appearance-none outline-none dark:text-gray-100 bg-dark disabled:bg-gray-100 focus:outline-none focus:ring-orange-500 focus:border-orange-500 sm:text-sm",
						className,
					)}
					{...props}
				/>
			</div>
		</div>
	);
}

export function Label({ children }) {
	return (
		<label htmlFor="name" className="block text-sm font-medium text-gray-600 dark:text-gray-300">
			{children}
		</label>
	);
}
